name: Inspect

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Init Stuff
      uses: ./.github/actions/init
    - name: Build
      shell: bash
      run: npm run build
